# Generated by Django 2.2.4 on 2020-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MauiMoviesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
