# Generated by Django 2.2.4 on 2020-11-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MauiMoviesApp', '0003_auto_20201123_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='heading',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='MauiMoviesApp.Review')),
            ],
        ),
    ]
