# Generated by Django 2.2.4 on 2020-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MauiMoviesApp', '0004_auto_20201124_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mmc_score',
            field=models.IntegerField(null=True),
        ),
    ]
