# Generated by Django 2.2.4 on 2020-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MauiMoviesApp', '0005_movie_mmc_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten_t',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
