# Generated by Django 2.2.4 on 2020-11-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MauiMoviesApp', '0006_auto_20201130_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieManager',
        ),
    ]
